# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-12 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
