# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-16 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='serious_profile_image',
            field=models.FileField(null=True, upload_to='profiles'),
        ),
    ]
