# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-19 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180916_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gluten', models.BooleanField(default=False)),
                ('lactose', models.BooleanField(default=False)),
                ('milk', models.BooleanField(default=False)),
                ('nuts', models.BooleanField(default=False)),
                ('shellfish', models.BooleanField(default=False)),
                ('celery', models.BooleanField(default=False)),
                ('soy', models.BooleanField(default=False)),
                ('fish', models.BooleanField(default=False)),
                ('egg', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
                ('pescitarian', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('not_swine', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Allergies',
                'default_related_name': 'allegies',
            },
        ),
    ]
