# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-19 17:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_allergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergy',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='allegies', to=settings.AUTH_USER_MODEL),
        ),
    ]
