# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-19 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_allergy_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='serious_profile_image',
            field=models.FileField(blank=True, null=True, upload_to='profiles'),
        ),
    ]
