# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-19 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180919_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='in_relationship',
            field=models.BooleanField(default=False),
        ),
    ]
